# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=50)),
                ('need_spiner', models.BooleanField()),
                ('engine', models.CharField(max_length=150)),
                ('socket_engine', models.CharField(max_length=150)),
            ],
        ),
    ]
