# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_invoker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='engine',
            new_name='engines',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='socket_engine',
            new_name='socket_engines',
        ),
    ]
