{"site": "yandex", "img": "http://www.slackware.ru/mediawiki/images/9/97/Kernel_079.png"}
{"site": "yandex", "img": "http://www.slackware.ru/mediawiki/images/3/33/Kernel_044.png"}
{"site": "yandex", "img": "http://1.bp.blogspot.com/-yVqM94SlZRw/UWp5jB-51LI/AAAAAAAAAOY/7VBm9yl1D4Y/s1600/conf-folder.jpg"}
{"site": "yandex", "img": "http://www.conformato.com/wp-content/uploads/sites/7/2015/01/600h320.png"}
{"site": "yandex", "img": "http://centos.name/media/phpmyadmin.conf.jpg"}
{"site": "yandex", "img": "https://ejesconsulting.files.wordpress.com/2009/07/rc-conf-transmission_blocklistyes.png"}
{"site": "yandex", "img": "http://www.viapark.it/wp-content/uploads/2015/12/conf.png"}
{"site": "yandex", "img": "http://root-nation.com/wp-content/uploads/2015/02/Conf1.jpg"}
{"site": "yandex", "img": "https://memo-linux.com/wp-content/uploads/2014/02/pydio-07.png"}
{"site": "yandex", "img": "http://gang-cs.com/01/09/488.jpg"}
